### ISSUE TITLE
Validators aliasing

### ISSUE THREAD

**Issue by bfontaine** [gajus/vlad#8]
Let validators declare a keyword to be called with instead of their full namespaced-name, e.g.:

``` php
$test->assert("foo")
     ->is("base64");
```

instead of:

``` php
$test->assert("foo")
     ->is("\My\Long\Namespace\Base64");
```

**Comment by gajus** [comment]
This would require some sort of `alias` method.

``` php
$test = new \Gajus\Vlad\Test();
$test->alias('My\Long\Namespace\Base64', 'Base64');
$test->assert('foo')->is('Base64');
```

The problem with the above is that as long as alias is Test specific, it is not much useful.

Alternatively, `Test` could lookup up static variable, e.g.

``` php
\Gajus\Vlad\Test::alias('My\Long\Namespace\Base64', 'Base64');
$test = new \Gajus\Vlad\Test();
$test->assert('foo')->is('Base64');
```

The problem with the above is that it would introduce a global state.

Final alternative would be to have user land class that defines those aliases, e.g.

``` php
class MyTest extends \Gajus\Vlad\Test {
    public function __construct (\Gajus\Vlad\Translator $translator = null) {
        parent::__construct($translator);
        $this->alias('My\Long\Namespace\Base64', 'Base64');
    }
}
```
